# Generated by Django 5.2.4 on 2025-08-07 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangosense', '0002_mangoimage_disease_classification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('predicted_disease', models.CharField(max_length=50)),
                ('user_feedback', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_accuracy', models.FloatField(blank=True, null=True)),
                ('location_consent_given', models.BooleanField(default=False)),
                ('location_address', models.TextField(blank=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_confirmation', to='mangosense.mangoimage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confirmed_at'],
            },
        ),
    ]
