# Generated by Django 5.2.4 on 2025-08-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangosense', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionlog',
            name='labels',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='prediction_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='probabilities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
