# Generated by Django 5.2.4 on 2025-08-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangosense', '0005_predictionlog_labels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionlog',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
